### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by luishdez** [sous-chefs/mongodb#31]
A basic initial roadmap
- [x] Setup travis
- [x] Update README.md regarding the fork and travis badge ( follow apache 2.0 LICENSE )
- [x] Fix travis build for ruby 1.9.3 https://github.com/chef-brigade/mongodb-cookbook/issues/34 in order to have CI
- [ ] Update metadata.rb and submit to market. Which name should we use? Discussion: https://github.com/chef-brigade/meta/issues/3
- [x] Review and tag pending pull requests
- [x] Define an strategy to clean PRs
- [ ] Merge/Clean easy PRs
- [ ] Support for MongoDB >3.0 Branch: https://github.com/chef-brigade/mongodb-cookbook/tree/mongodb-v3

**Comment by luishdez** [comment]
@josephholsten, I need your approval in order to setup travis. I did a request to grant access. Though I guess you can setup travis easily as you are the original owner of the organization.

Anyways I hope that the original repo can be transferred ...

**Comment by josephholsten** [comment]
Travis setup: approved!

**Comment by luishdez** [comment]
Ok, I've been reviewing a little bit all pending PRs, tagged some…

There are a few very complex PRs for main things like sharding/replicaset that are very distant in time "some of them from 2013"… Those are PRs against the master and they conflict with each other. Merging that is too complex.

Check this PRs: https://github.com/chef-brigade/mongodb-cookbook/labels/comp%3A%20replicaset

A possible strategy would be:

1. Locate, tag and merge the easy PRs for quick fixes. Like basic features, bugs, and compatibilities. This PRs are easy to merge right now.
2. Drop the complex PRs and work in a new branch for each "main" feature by order. 
  1. Replicaset/sharding
  2. User management
  3. Backups

The idea is not to drop all the code from PRs but taking the initial ideas or pieces that we can use. IMHO Working in a clean slate is going to be much easy.

**Comment by damacus** [comment]
I think this is a good start for the 1.0.0 rewrite. @shortdudey123 will probably write another set of issues in the bug track for it if we've missed anything! 

Please see the milestone for progress https://github.com/sous-chefs/mongodb/milestone/2
